### ISSUE TITLE
The file is missing

### ISSUE THREAD

**Issue by tongchangD** [thecharm/boundary-aware-nested-ner#2]
留名

**Comment by thecharm** [comment]
We have given the Download Link for GENIA pretrained word embeddings in README.md. [https://drive.google.com/file/d/0BzMCqpcgEJgiUWs0ZnU0NlFTam8/view](url)

**Comment by tongchangD** [comment]
thanks for your reply.
I can't get into the website you provided. need over the wall？










At 2020-05-27 15:16:39, "thecharm" <notifications@github.com> wrote:

We have given the Download Link for GENIA pretrained word embeddings in README.md. https://drive.google.com/file/d/0BzMCqpcgEJgiUWs0ZnU0NlFTam8/view

**Comment by thecharm** [comment]
Yes, you need a VPN to download it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tongchangD"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 上午9:05
收件人:&nbsp;"thecharm/boundary-aware-nested-ner"<boundary-aware-nested-ner@noreply.github.com&gt;;
抄送:&nbsp;"华南理工大学_CIKETheCharm"<1019905125@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [thecharm/boundary-aware-nested-ner] The file is missing (#2)





 thanks for your reply.
 I can't get into the website you provided. need over the wall？
 
 
 
 
 
 
 
 
 
 
 At 2020-05-27 15:16:39, "thecharm" <notifications@github.com&gt; wrote:
 
 We have given the Download Link for GENIA pretrained word embeddings in README.md. https://drive.google.com/file/d/0BzMCqpcgEJgiUWs0ZnU0NlFTam8/view

**Comment by zxk19981227** [comment]
you didn't release it，right？

**Comment by thecharm** [comment]
Just copy the link above and open it in your browser, I have checked it the link is still available (you should download it via google drive)

**Comment by zxk19981227** [comment]
yeah, it is available. But i should apply for the access. I think you set the file in a wrong share way

**Comment by thecharm** [comment]
OK, I got it. The new link: https://drive.google.com/file/d/0BzMCqpcgEJgiUWs0ZnU0NlFTam8/view?usp=sharing&resourcekey=0-hKMdnLPkaFZZYNiIMeyoww 
Thanks for your comments. I will update the README file.
