### ISSUE TITLE
Need some help for the embedding.npy

### ISSUE THREAD

**Issue by JackySnake** [thecharm/boundary-aware-nested-ner#4]
Thank you for the excellent work!

I am tring to run the train.py. But the EMBED_URL file in the train, which is needed to bulid the model is missing. This file is not in the google driver bio_nlp_vec.tar.gz. Would you provide this file? 

In addition, where can I get the iob2 format 'Germ' dataset? The link in README is bad.

Thank you again.

**Comment by thecharm** [comment]
Just run the dataset.py you will get the embedding.npy file.
Germeval 2014 dataset: https://sites.google.com/site/germeval2014ner/
