### ISSUE TITLE
region_labels 

### ISSUE THREAD

**Issue by cpmss521** [thecharm/boundary-aware-nested-ner#6]
https://github.com/thecharm/boundary-aware-nested-ner/blob/477bd138a3a849d0c16e9e05202bee3f2eb00749/Our_boundary-aware_model/dataset.py#L57
https://github.com/thecharm/boundary-aware-nested-ner/blob/477bd138a3a849d0c16e9e05202bee3f2eb00749/Our_boundary-aware_model/dataset.py#L62
这两行之间实现的region_labels代表什么意思啊？谢谢，不太明白嵌套试实体的标签怎么表示的，希望赐教。

**Comment by cpmss521** [comment]
I'm so sorry. I got it. thanks!

**Comment by LLLLLLoki** [comment]
这个label表示什么意思啊-，-没看太明白，兄弟能抽空解释一下吗
